### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by ChubbyBalboa** [kfichter/ez-harvest#1]
Hi,

I'm trying to use this for supreme but its not showing any Captchas, it's just opening a blank window.

**Comment by kfichter** [comment]
I haven't maintained this in a while, sorry. It may not still be working.

**Comment by ChubbyBalboa** [comment]
> I haven't maintained this in a while, sorry. It may not still be working.

Are there any other solutions that don't require changing the hosts file?

**Comment by kfichter** [comment]
I honestly have no clue. Don't really work on sneaker stuff anymore.

**Comment by ChubbyBalboa** [comment]
Alright, thanks.
